// <auto-generated />
namespace HumberAutoCarRental.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddCarTypeCar : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCarTypeCar));
        
        string IMigrationMetadata.Id
        {
            get { return "202102111835127_Add-CarType-Car"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
